//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/InputAction/PlayerInputAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputAction: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputAction"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""a6323123-fab1-4615-9518-69be057e2706"",
            ""actions"": [
                {
                    ""name"": ""Interaction"",
                    ""type"": ""Button"",
                    ""id"": ""a6623de5-4e37-4b7d-8839-e8f081df757e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""e57c1005-51ba-4914-bdf6-f89d5cbb8a6e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""78778e90-7f13-4e4d-88c0-3347a421a265"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""2eee573a-fad4-4fd4-8fcd-53f64d442d8f"",
                    ""expectedControlType"": ""Delta"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""2b35d0e7-e464-4458-bc3d-d678613ed66f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""dd199d97-f33c-4fad-98bf-554bddc7d2d4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OneInvne"",
                    ""type"": ""Button"",
                    ""id"": ""d21db4cc-6302-4c14-af52-9af3bc03e6c3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TwoInven"",
                    ""type"": ""Button"",
                    ""id"": ""e166f5f9-8f8d-4000-81d6-ae2d3de0f9c9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThreeInven"",
                    ""type"": ""Button"",
                    ""id"": ""9a27feff-714f-4be2-b58f-a463aa32f097"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FourInven"",
                    ""type"": ""Button"",
                    ""id"": ""2a012903-6c81-4db2-a1ee-c6dd0d18884b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FiveInven"",
                    ""type"": ""Button"",
                    ""id"": ""4b96154b-f86c-4141-aff7-a33aa294093f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SixInven"",
                    ""type"": ""Button"",
                    ""id"": ""4755efe2-a32a-4942-92cc-8c4bc397b96b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SevenInven"",
                    ""type"": ""Button"",
                    ""id"": ""260206a2-9b12-4ceb-a7a4-f85b97576690"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EightInven"",
                    ""type"": ""Button"",
                    ""id"": ""a8680cde-a97e-429c-9cb7-7032069733c1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ee35fe65-d9f4-4a42-b4e0-b90203afe378"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""6864a1cc-dadb-48e0-b9bf-38a37556eee9"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e833d4fd-5604-4110-a1f4-b38ba909ea1f"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""3aff6794-4cc6-4152-8ec9-d451e34987c0"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""ac25bb87-e70f-416a-8cad-1b43be15d6f7"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""de38c839-1964-4025-b6a8-b588d22b5153"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e16d6123-4b8e-47b1-ac63-953f0c1ddd41"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""de4ab757-2527-4771-9b8e-5f249ebb4437"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba7f52a7-2201-41d7-8b8e-404b0056f25b"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5ff52f67-064d-4633-a3e8-2ec3fbac582b"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""059b7491-8cec-401a-8118-ef70c6ab6656"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8ffd900-b863-4188-b6f0-8231885c259b"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OneInvne"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b34a5e2e-45a2-4dd9-aa19-a015f72bce3e"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TwoInven"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f70ce5b9-8b0c-4da9-961a-ad2f8636f1e4"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThreeInven"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""358d7999-7d6a-4ba4-8dbc-bad1150e6b2e"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FourInven"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d75062c7-b507-4176-8399-e2517c4d9cdd"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FiveInven"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""23c5bc3b-1c82-452d-90de-4bcd30d3f8e1"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SixInven"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6e405ab7-46ca-4b96-b38a-ef4c689e4100"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SevenInven"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f7730313-9472-4773-9c7b-3e13cd9a3a4d"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EightInven"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Interaction = m_Player.FindAction("Interaction", throwIfNotFound: true);
        m_Player_Cancel = m_Player.FindAction("Cancel", throwIfNotFound: true);
        m_Player_Movement = m_Player.FindAction("Movement", throwIfNotFound: true);
        m_Player_Look = m_Player.FindAction("Look", throwIfNotFound: true);
        m_Player_Run = m_Player.FindAction("Run", throwIfNotFound: true);
        m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
        m_Player_OneInvne = m_Player.FindAction("OneInvne", throwIfNotFound: true);
        m_Player_TwoInven = m_Player.FindAction("TwoInven", throwIfNotFound: true);
        m_Player_ThreeInven = m_Player.FindAction("ThreeInven", throwIfNotFound: true);
        m_Player_FourInven = m_Player.FindAction("FourInven", throwIfNotFound: true);
        m_Player_FiveInven = m_Player.FindAction("FiveInven", throwIfNotFound: true);
        m_Player_SixInven = m_Player.FindAction("SixInven", throwIfNotFound: true);
        m_Player_SevenInven = m_Player.FindAction("SevenInven", throwIfNotFound: true);
        m_Player_EightInven = m_Player.FindAction("EightInven", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Interaction;
    private readonly InputAction m_Player_Cancel;
    private readonly InputAction m_Player_Movement;
    private readonly InputAction m_Player_Look;
    private readonly InputAction m_Player_Run;
    private readonly InputAction m_Player_Jump;
    private readonly InputAction m_Player_OneInvne;
    private readonly InputAction m_Player_TwoInven;
    private readonly InputAction m_Player_ThreeInven;
    private readonly InputAction m_Player_FourInven;
    private readonly InputAction m_Player_FiveInven;
    private readonly InputAction m_Player_SixInven;
    private readonly InputAction m_Player_SevenInven;
    private readonly InputAction m_Player_EightInven;
    public struct PlayerActions
    {
        private @PlayerInputAction m_Wrapper;
        public PlayerActions(@PlayerInputAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @Interaction => m_Wrapper.m_Player_Interaction;
        public InputAction @Cancel => m_Wrapper.m_Player_Cancel;
        public InputAction @Movement => m_Wrapper.m_Player_Movement;
        public InputAction @Look => m_Wrapper.m_Player_Look;
        public InputAction @Run => m_Wrapper.m_Player_Run;
        public InputAction @Jump => m_Wrapper.m_Player_Jump;
        public InputAction @OneInvne => m_Wrapper.m_Player_OneInvne;
        public InputAction @TwoInven => m_Wrapper.m_Player_TwoInven;
        public InputAction @ThreeInven => m_Wrapper.m_Player_ThreeInven;
        public InputAction @FourInven => m_Wrapper.m_Player_FourInven;
        public InputAction @FiveInven => m_Wrapper.m_Player_FiveInven;
        public InputAction @SixInven => m_Wrapper.m_Player_SixInven;
        public InputAction @SevenInven => m_Wrapper.m_Player_SevenInven;
        public InputAction @EightInven => m_Wrapper.m_Player_EightInven;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Interaction.started += instance.OnInteraction;
            @Interaction.performed += instance.OnInteraction;
            @Interaction.canceled += instance.OnInteraction;
            @Cancel.started += instance.OnCancel;
            @Cancel.performed += instance.OnCancel;
            @Cancel.canceled += instance.OnCancel;
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @Run.started += instance.OnRun;
            @Run.performed += instance.OnRun;
            @Run.canceled += instance.OnRun;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @OneInvne.started += instance.OnOneInvne;
            @OneInvne.performed += instance.OnOneInvne;
            @OneInvne.canceled += instance.OnOneInvne;
            @TwoInven.started += instance.OnTwoInven;
            @TwoInven.performed += instance.OnTwoInven;
            @TwoInven.canceled += instance.OnTwoInven;
            @ThreeInven.started += instance.OnThreeInven;
            @ThreeInven.performed += instance.OnThreeInven;
            @ThreeInven.canceled += instance.OnThreeInven;
            @FourInven.started += instance.OnFourInven;
            @FourInven.performed += instance.OnFourInven;
            @FourInven.canceled += instance.OnFourInven;
            @FiveInven.started += instance.OnFiveInven;
            @FiveInven.performed += instance.OnFiveInven;
            @FiveInven.canceled += instance.OnFiveInven;
            @SixInven.started += instance.OnSixInven;
            @SixInven.performed += instance.OnSixInven;
            @SixInven.canceled += instance.OnSixInven;
            @SevenInven.started += instance.OnSevenInven;
            @SevenInven.performed += instance.OnSevenInven;
            @SevenInven.canceled += instance.OnSevenInven;
            @EightInven.started += instance.OnEightInven;
            @EightInven.performed += instance.OnEightInven;
            @EightInven.canceled += instance.OnEightInven;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Interaction.started -= instance.OnInteraction;
            @Interaction.performed -= instance.OnInteraction;
            @Interaction.canceled -= instance.OnInteraction;
            @Cancel.started -= instance.OnCancel;
            @Cancel.performed -= instance.OnCancel;
            @Cancel.canceled -= instance.OnCancel;
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @Run.started -= instance.OnRun;
            @Run.performed -= instance.OnRun;
            @Run.canceled -= instance.OnRun;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @OneInvne.started -= instance.OnOneInvne;
            @OneInvne.performed -= instance.OnOneInvne;
            @OneInvne.canceled -= instance.OnOneInvne;
            @TwoInven.started -= instance.OnTwoInven;
            @TwoInven.performed -= instance.OnTwoInven;
            @TwoInven.canceled -= instance.OnTwoInven;
            @ThreeInven.started -= instance.OnThreeInven;
            @ThreeInven.performed -= instance.OnThreeInven;
            @ThreeInven.canceled -= instance.OnThreeInven;
            @FourInven.started -= instance.OnFourInven;
            @FourInven.performed -= instance.OnFourInven;
            @FourInven.canceled -= instance.OnFourInven;
            @FiveInven.started -= instance.OnFiveInven;
            @FiveInven.performed -= instance.OnFiveInven;
            @FiveInven.canceled -= instance.OnFiveInven;
            @SixInven.started -= instance.OnSixInven;
            @SixInven.performed -= instance.OnSixInven;
            @SixInven.canceled -= instance.OnSixInven;
            @SevenInven.started -= instance.OnSevenInven;
            @SevenInven.performed -= instance.OnSevenInven;
            @SevenInven.canceled -= instance.OnSevenInven;
            @EightInven.started -= instance.OnEightInven;
            @EightInven.performed -= instance.OnEightInven;
            @EightInven.canceled -= instance.OnEightInven;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnInteraction(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
        void OnMovement(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnOneInvne(InputAction.CallbackContext context);
        void OnTwoInven(InputAction.CallbackContext context);
        void OnThreeInven(InputAction.CallbackContext context);
        void OnFourInven(InputAction.CallbackContext context);
        void OnFiveInven(InputAction.CallbackContext context);
        void OnSixInven(InputAction.CallbackContext context);
        void OnSevenInven(InputAction.CallbackContext context);
        void OnEightInven(InputAction.CallbackContext context);
    }
}
